// Rebuild docs/CORE.md after moving a tagged implementation line.
import { readdirSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve("src");
const files = [];
function walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (/\.(ts|tsx)$/.test(entry.name)) files.push(full);
  }
}
walk(root);

const order = ["RULES", "SEAL", "CLOSE", "PRED", "ELO", "INTEREST", "PLAN", "GATE", "CTX", "DELIB", "CHECK", "SAFE"];
const questions = {
  RULES: "How do you know the game is fair and solvable?",
  SEAL: "How can the player verify Venn moved first?",
  CLOSE: "How do you measure progress without revealing links?",
  PRED: "How does Venn predict this player's click?",
  ELO: "How do strengths and blind spots emerge quickly?",
  INTEREST: "How do stated and revealed interests differ?",
  PLAN: "How does Venn choose a legal move?",
  GATE: "When do you spend an LLM call?",
  CTX: "Why does this memory belong in the prompt?",
  DELIB: "What judgment does the LLM actually make?",
  CHECK: "What happens when model output is wrong?",
  SAFE: "Where are the trust and privacy boundaries?",
};
const rows = [];
for (const file of files) {
  const lines = readFileSync(file, "utf8").split(/\r?\n/);
  lines.forEach((line, index) => {
    const hit = line.match(/CORE-([A-Z]+)-(\d+):\s*(.*)/);
    if (!hit) return;
    let what = hit[3].trim();
    for (let next = index + 1; next < lines.length && /^\s*\/\//.test(lines[next]) && !/[.!?]$/.test(what); next++) {
      what += ` ${lines[next].replace(/^\s*\/\/\s?/, "").trim()}`;
    }
    rows.push({ area: hit[1], number: Number(hit[2]), tag: `CORE-${hit[1]}-${hit[2]}`, file: path.relative(process.cwd(), file).replaceAll("\\", "/"), line: index + 1, what: what.replaceAll("|", "\\|") });
  });
}
rows.sort((a, b) => order.indexOf(a.area) - order.indexOf(b.area) || a.number - b.number);
const duplicate = rows.find((row, i) => rows.findIndex(other => other.tag === row.tag) !== i);
if (duplicate) throw new Error(`Duplicate tag: ${duplicate.tag}`);
const doc = [
  "# Common Ground: core walkthrough",
  "",
  "Read from the rules and seal through measurement, learning, planning, context, model checks, and safety. The tagged comments mark the formulas, thresholds, fallbacks, and trust boundaries worth explaining in an interview. Line numbers are regenerated by `node scripts/core-index.mjs`.",
  "",
  "| Tag | File:line | What it does | Likely interview question |",
  "|---|---|---|---|",
  ...rows.map(r => `| ${r.tag} | [${r.file}:${r.line}](../${r.file}#L${r.line}) | ${r.what} | ${questions[r.area] ?? "Why does this matter?"} |`),
  "",
].join("\n");
mkdirSync("docs", { recursive: true });
writeFileSync("docs/CORE.md", doc);
console.log(`Indexed ${rows.length} core tags in docs/CORE.md`);
